### PR TITLE
Initial src directory structure

### LINKED ISSUE #1: Define directory structure conventions
A couple of things to consider here:

- Modularity, e.g. is it worth separating out scripts in some way?
- Versioning, i.e. to support fetching scripts from pipelines with curl while preserving ability to make breaking changes

### PR DESCRIPTION
**Pull request by jt-nti**
Initial src directory structure

These scripts will be bundled up in to a versioned tarball for
use from toolchain pipelines

Scripts directly under the src directory should be used in
pipeline jobs as follows:

source "${SCRIPT_DIR}/BUILD.sh"

Scripts under the common directory should contain functions for
use by pipeline build scripts

Scripts under other subdirectories should contain
contract/chaincode specific implementations of the pipeline build
scripts

Also includes placeholder test scripts and travis build

Closes #1

Signed-off-by: James Taylor <jamest@uk.ibm.com>

### CODE REVIEW

**Review by jorgedr94 — CHANGES_REQUESTED** [review]
Hi James, 

Few comments:

1.  Can we use a case convention for scripts.    Can we use lower case for all script names and - when multiple words are use? 

2.   I think that we should follow the same convention for prepare.sh that  we used for build, test, deploy.  Meaning that we should have a prepare.sh at the top level src/prepare.sh and have that script decide how to prepare for each platform buy calling the scripts under the composer or fabric directories. If we find commonality on both as we develop we can refactor into  the common library.

**Comment by jorgedr94** [comment]
One last comment, I liked how you called go-chaincode for the directory name that holds the scripts. In reality js-chaincode will also be a thing and  at least I can see that building and testing will be different for that type of chaincode.

**Comment by jt-nti** [comment]
@jorgedr94 

1. lower case script names and '-' sound ok to me. They seemed to match the pipeline case in Simon's prototype. I'm tempted to move them down in a 'pipeline' directory to clarify instead (the 'pipeline-' prefixes seemed a bit repetitive anyway)

2. the prepare script is definitely not a pipeline script and should only be to bootstrap the whole process, i.e. there would not be any platform specific versions. Maybe it needs a different name to differentiate it from the prepare pipeline- bootstrap.sh perhaps

**Review by jorgedr94 — COMMENTED** [review]
Looks great!

**Review by jorgedr94 — DISMISSED** [review]

**Review by jorgedr94 — APPROVED** [review]

**Pull request merged**
